CREATE TABLE users (
id INT(11) NOT NULL AUTO_INCREMENT,
firstName VARCHAR(45) NOT NULL,
lastName VARCHAR(45) NOT NULL,
dateOfBirth TIMESTAMP default CURRENT_TIMESTAMP,
PRIMARY KEY(id));

CREATE TABLE phones (
id INT(11) NOT NULL AUTO_INCREMENT,
countryCode VARCHAR(45),
innerNUmber VARCHAR(45),
userId 	int(11) NOT NULL,
PRIMARY KEY(id)
);